" ## Basics
set nocompatible
set showcmd
filetype plugin indent on   " Add filetype, plugin, indent support
syntax on       " Turn on syntax highlighting

" ## Settings
set backspace=indent,eol,start    " Allow to backspace everything in insert mode
set wildmenu        " Display matches in command-line mode
set expandtab       " Prefer tabs over spaces
set tabstop=2 softtabstop=2   " Set tab size to 2
set shiftwidth=2
set smartindent
set tabstop=2 softtabstop=2   " Set tab size to 2
set shiftwidth=2
set smartindent
set hidden        " Prefer hiding over unloading buffers
set path=.,**       " Relative to current file and everything under :pwd
setl wildignore=**/node_modules/**,**/dist/**
set noswapfile
let mapleader = " "     " Space as <leader>
set encoding=utf-8
set fileencoding=utf-8
set ruler                               " Show cursor position at all times
set cursorline                          " Highlight current line
set cursorlineopt=line
set cmdheight=2                         " more space for displaying messages
set splitbelow splitright
set t_Co=256
set laststatus=2                        " Always show status line
set showtabline=2                       " Always show tab line
set updatetime=300
set timeoutlen=500
set clipboard=unnamed
set colorcolumn=80
set scrolloff=5
set pumheight=10
set nowrap


" ## Keyboard mappings
vnoremap . :        " Period is easier to reach on swedish keyboard
vnoremap : .
nnoremap . :
nnoremap : .

" Set up keybindings for asyncomplete
inoremap <expr> <Down> pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr> <Up>   pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr> <CR>   pumvisible() ? asyncomplete#close_popup() : "\<CR>"
inoremap <expr> <Tab>  pumvisible() ? asyncomplete#close_popup() : "\<Tab>"

" Change window with <C-hjkl>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Resize windows with <A-HJKL>
nnoremap <A-h> :vertical resize +2<CR>
nnoremap <A-j> :resize -2<CR>
nnoremap <A-k> :resize +2<CR>
nnoremap <A-l> :vertical resize -2<CR>

" Switch tabs with <leader>n and <leader>p
nnoremap <Tab>   :tabn<CR>
nnoremap <S-Tab>   :tabp<CR>
" Allow for alt-key in WSL/Windows terminal
let c='a'
while c <= 'z'
  exec "set <A-".c.">=\e".c
  exec "imap \e".c." <A-".c.">"
  let c = nr2char(1+char2nr(c))
endw
set ttimeout ttimeoutlen=50

colorscheme PaperColor

" Configure lightline
let g:lightline = { 'colorscheme': 'PaperColor', } 

augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave,WinEnter *.ts,*.html if &nu && mode() != "i" | set rnu    | endif
	autocmd BufLeave,FocusLost,InsertEnter,WinLeave   *.ts,*.html if &nu                  | set nornu  | endif
augroup END
